// <auto-generated />
using EntityFrameworkDPSLibrary.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkDPSLibrary.Migrations
{
    [DbContext(typeof(MFSDbContext))]
    [Migration("20211202122250_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkDPSLibrary.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InvoiceCode");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("EntityFrameworkDPSLibrary.Models.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductCode");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
